func test() {
	a = "Hello A";
	println(a);
	delete(a);
	println(a);
}
try { test(); }
catch err { println("SUCCESS! Received expected error: ", err); }

b = "Hello B";
println(b);
delete(b);
println("An error will now occur...");
println(b);
