try {
	println("block 1 fails...");
	throw;
}
else {
	println("block 2 fails...");
	throw;
}
else {
	println("block 3 succeeds!");
}
else {
	println("block 4 is never tried, some previous block has succeeded.");
	throw "this will not be thrown";
}
else {
	println("block 5 is never tried, some previous block has succeeded.");
	throw "this will not be thrown either";
}
catch err {
	println("No error should have been thrown: err = ", err);
}

try {
	println("block 1 fails...");
	throw;
}
else {
	println("block 2 fails...");
	throw;
}
else {
	println("block 3 throws an exception.");
	throw "exception in block 3";
}
else {
	println("block 4 is never tried, some previous block has thrown a non-void exception.");
	throw "this will not be thrown";
}
else {
	println("block 5 is never tried, some previous block has thrown a non-void exception.");
	throw "this will not be thrown either";
}
catch err {
	println("Only the exception in block 3 should have been thrown");
	println("err = ", err);
}

